spring:
  application:
    name: ShadowCard

  datasource:
    url: jdbc:postgresql://localhost:5432/shadowcard
    username: kangj
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  type-aliases-package: com.loafman.shadowcard.model
  mapper-locations: classpath:mapper/*.xml
